#!/bin/sh

FILE=array2d
cd ../library && mmc -x ${FILE}.m
cd ../doc
xsltproc --stringparam module "${FILE}" library.xslt ../library/${FILE}.xml | \
	sed -n  -e 's/^[ \t]\+//g'		\
		-e 's/^%[ \t]//g' 		\
		-e '/^vim: /d'			\
		-e '/^%--*--% */d'		\
		-e 's/^%[ \t]*//g'		\
		-e '/^File: /d'			\
		-e 'p'
